extends SceneTree
## Headless controller/evidence contract; does not establish native visual comfort.
const Explanation = preload("res://experiments/creation/explanation.gd")
const Model = preload("res://experiments/creation/model.gd")
var failures: int = 0
var checks: int = 0
func _init() -> void: call_deferred("run")
func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok: failures += 1; push_error(message)
func settle() -> void:
	for frame: int in 6: await process_frame
func run() -> void:
	var scene = load("res://experiments/creation/workbench.tscn").instantiate()
	root.add_child(scene); await settle()
	root.mode = Window.MODE_WINDOWED; root.size = Vector2i(1280,720); root.content_scale_size = Vector2i(1280,720)
	await settle()
	var session = scene.session
	scene.train_model(); await settle()
	check(not scene.latest.rule_changes.is_empty(),"First training exposes actual rule counts from zero")
	check(scene.causal_tabs.current_tab == scene.causal_panel.get_index(),"Training opens causal details")
	check(not scene.causal_panel.audit_label.visible,"Training audit is folded")
	scene.train_model(); await settle()
	check(scene.latest.rule_changes.is_empty(),"Relearning unchanged examples has no invented delta")
	var before: Dictionary = session.data.model.duplicate(true)
	session.data.draft.examples = [[0,1,0,3],[0,1,0,3]]
	scene.train_model(); await settle()
	var changes: Array = Explanation.rule_changes(before,session.data.model)
	check(scene.latest.rule_changes == changes,"UI delta binds before/after frozen models")
	check(not changes.is_empty(),"Changed examples produce actual changed counts")
	check(Explanation.rule_changes(session.data.model,session.data.model).is_empty(),"Identical snapshot diff is empty")
	var removed: Array = Explanation.rule_changes(session.data.model,{})
	check(not removed.is_empty() and removed[0].removed,"Removed rules explicitly represented")
	var rule: TreeItem = scene.rules.get_root().get_first_child()
	var frozen_counts: Array = rule.get_metadata(0).counts.duplicate()
	rule.select(0); scene.inspect_rule(); await settle()
	check(scene.causal_panel.raw_record.counts == frozen_counts,"Rule row opens authoritative frozen counts")
	check(scene.focused_cell == -1,"Rule inspection does not mislabel a signal position")
	scene.transport("predictive"); await settle()
	scene.inspect_cell(4); await settle()
	check(scene.signal_view.selected == 4 and scene.focused_cell == 4,"Selected cell is visibly anchored")
	check(scene.causal_panel.candidates.get_child_count() == 4,"Actual four candidate counts shown")
	check(scene.causal_panel.get_global_rect().encloses(scene.causal_panel.candidates.get_global_rect()),"All candidate bars visible before scrolling")
	check(scene.causal_panel.audit_label.visible == false,"Cell audit defaults folded")
	check(scene.causal_panel.summary_label.text.contains("预测"),"Compact causal explanation replaces JSON")
	check(scene.inspector.text.contains("预测") and scene.inspector.text.contains("实际"),"Context-to-result chain remains beside the signal")
	check(not scene.inspector.text.contains("{"),"Top inspector avoids raw JSON")
	check(root.get_visible_rect().encloses(scene.causal_panel.get_global_rect()),"Causal tab stays within 1280x720")
	check(scene.causal_panel.get_global_rect().size.y >= 48,"Candidate bars have a visible row at minimum size")
	scene.causal_panel.audit_toggle.button_pressed = true
	check(scene.causal_panel.audit_label.visible and scene.causal_panel.audit_label.text.contains("predicted"),"User can expose original audit")
	scene.inspect_cell(3)
	check(not scene.causal_panel.audit_label.visible,"New evidence folds audit again")
	scene.switch_mode("predict"); scene.begin_prediction("practice"); scene.commit_prediction(); await settle()
	var pending_index: int = session.prediction.prefix.size()
	scene.inspect_cell(pending_index); await settle()
	check(scene.causal_panel.summary_label.text.contains("尚未揭晓"),"Pending display does not invent a truth")
	check(not scene.causal_panel.raw_record.has("truth"),"Pending raw audit has no hidden truth")
	check(scene.signal_view.context_count == session.prediction.pending.context.size(),"Highlight follows actually matched context length")
	var selected_counts: Array = session.prediction.pending.counts.duplicate()
	for i: int in 4:
		check(scene.causal_panel.candidates.get_child(i).get_child(1).value == selected_counts[i],"Candidate bar equals recorded count")
	scene.reveal_prediction(); await settle()
	check(scene.focused_cell == pending_index and scene.signal_view.selected == pending_index,"Reveal preserves selected position")
	check(scene.causal_panel.raw_record.has("truth"),"Reveal updates same cell with actual truth")
	scene.toggle_language(); await settle()
	check(scene.focused_cell == pending_index and scene.causal_panel.summary_label.text.contains("Actual"),"Language rebuild retains selected truth and focus")
	scene.toggle_language(); await settle()
	scene.commit_prediction(); await settle()
	check(scene.focused_cell == pending_index,"Next commit keeps previously inspected cell")
	scene.begin_prediction("memorize"); scene.commit_prediction(); scene.inspect_cell(session.prediction.prefix.size()); await settle()
	check(scene.causal_panel.candidates.get_child_count() == 0,"Memorization never masquerades as learned candidate counts")
	scene.begin_prediction("practice"); await settle()
	check(not scene.inspector.text.contains("预测"),"New run clears old causal chain")
	check(scene.focused_cell == -1 and scene.causal_panel.raw_record.is_empty(),"New run clears stale selected evidence")
	scene.english = true; scene.build(); await settle()
	scene.commit_prediction(); scene.inspect_cell(session.prediction.prefix.size()); await settle()
	check(scene.causal_panel.summary_label.text.contains("not yet revealed"),"Alternate locale explains sealed state")
	check(scene.causal_panel.audit_toggle.text == "Show raw audit record","Audit control is localized")
	scene.queue_free(); await settle()
	print("%s: causal panel checks=%d failures=%d" % ["PASS" if failures == 0 else "FAIL",checks,failures])
	quit(0 if failures == 0 else 1)
