extends SceneTree

const PerformanceTask = preload("res://src/demo/demo_performance.gd")
const Foundations = preload("res://src/demo/demo_foundations.gd")
var failures: Array[String] = []

func _init() -> void:
	call_deferred("_run")

func check(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)
		push_error(message)

func capture(name: String) -> void:
	if "--capture-mainline" not in OS.get_cmdline_user_args():
		return
	await process_frame
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png("res://.godot/redesign/" + ("en-" if TranslationServer.get_locale().begins_with("en") else "") + name + ".png")

func _run() -> void:
	root.size = Vector2i(1600, 900)
	var mode := root.get_node("GameMode")
	check(not mode.is_test_mode(), "M1 uses ordinary Game without temporary workshop components.")
	var progress := root.get_node("DemoProgress")
	progress.game = progress._empty()
	var ui = load("res://src/demo/demo_workbench.tscn").instantiate()
	root.add_child(ui)
	await process_frame
	check(ui.task_id == "dp_select" and not progress.unlocked("d1_cpu"), "Fresh Game starts in P-1 with no workshop requirement.")
	await capture("m2-p1-initial")
	ui.run_current()
	check(not ui.completed, "Empty visible wiring cannot pass P-1.")
	wire(ui, "A", 0, "MUX", 0)
	wire(ui, "B", 0, "MUX", 1)
	wire(ui, "SEL", 0, "MUX", 2)
	wire(ui, "MUX", 0, "OUT", 0)
	ui.run_current()
	check(ui.completed, "Player wiring passes all P-1 behavior cases.")
	await capture("m2-p1-result")
	ui._continue_task()
	wire(ui, "DATA", 0, "REG", 0)
	wire(ui, "LOAD", 0, "REG", 1)
	wire(ui, "REG", 0, "Q", 0)
	ui.run_current()
	check(ui.completed, "Register write/hold stage completes.")
	ui._continue_task()
	wire(ui, "ADDR", 0, "RAM", 0)
	wire(ui, "DATA", 0, "RAM", 1)
	wire(ui, "WRITE", 0, "RAM", 2)
	wire(ui, "RAM", 0, "MEM", 0)
	ui.run_current()
	check(ui.completed, "Two addresses retain independent values while register holds.")
	ui._continue_task()
	wire(ui, "DATA", 0, "SOURCE", 0)
	wire(ui, "RAM", 0, "SOURCE", 1)
	wire(ui, "READ", 0, "SOURCE", 2)
	wire(ui, "SOURCE", 0, "REG", 0)
	wire(ui, "REG", 0, "RAM", 1)
	ui.run_current()
	check(ui.completed, "Visible LOAD/STORE path reads back both addresses.")
	await capture("m2-p2-result")
	ui._continue_task()
	check(not ui.editor.editable and not ui.run_button.disabled, "CPU task is runnable immediately and fixed program is read-only.")
	check(not ui.initial_run.is_empty() and ui.latest_run.is_empty(), "Authored baseline is distinct from player run.")
	await capture("m1-cpu-initial")
	ui.change_option("cpu", "cpu_fast")
	ui.run_button.pressed.emit()
	check(ui.completed and not ui.continue_button.disabled, "Completion is immediate with no prediction, playback or review lock.")
	check(ui.latest_run["metrics"]["total_cycles"] == 134, "Visible selection drives existing system simulation.")
	await capture("m1-cpu-result")
	ui.continue_button.pressed.emit()
	check(ui.task_id == "d1_upgrade", "CPU comparison continues to upgrade scenarios.")
	ui.change_option("cpu", "cpu_fast")
	ui.run_current()
	check(not ui.completed, "CPU upgrade fails RAM service target.")
	ui.change_option("cpu", "cpu_eco")
	ui.change_option("ram", "ram_fast")
	ui.run_current()
	check(ui.completed, "RAM upgrade solves scenario A.")
	ui._continue_task()
	ui.change_option("bus", "bus_8")
	ui.run_current()
	check(ui.completed, "Bus upgrade solves scenario B.")
	await capture("m3-upgrade-result")
	ui._continue_task()
	ui.change_option("bypass", false)
	ui.run_current()
	check(ui.completed, "Cache task sees a real first fetch and subsequent hits.")
	ui._continue_task()
	await process_frame
	check(ui.task_id == "d2_order" and ui.editor.editable, "Ordinary progression reaches access-order task.")
	ui.run_button.pressed.emit()
	check(not ui.completed and ui.latest_run["metrics"]["total_cycles"] == 321, "Initial poor cache behavior is observable.")
	ui._toggle_events()
	ui._next_event()
	await capture("m1-cache-initial")
	ui.editor.text = PerformanceTask.ROW_SOURCE
	ui.editor.text_changed.emit()
	ui.run_button.pressed.emit()
	check(ui.completed and ui.latest_run["metrics"]["total_cycles"] == 105, "One Run action validates and applies current draft.")
	var signature: String = ui.latest_run["signature"]
	ui._next_event()
	ui._next_event()
	check(signature == ui.latest_run["signature"], "Event inspection cannot alter results.")
	ui._toggle_replay()
	var cursor: int = ui.event_cursor
	ui.replay_speed.select(2)
	ui._process(0.2)
	check(ui.event_cursor == cursor + 1 and signature == ui.latest_run["signature"], "4x replay advances the same immutable trace without changing metrics.")
	ui.replay_position.value = 0
	check(not ui.replaying and ui.event_cursor == 0, "Seeking pauses playback and synchronizes the selected event.")
	ui._toggle_replay()
	ui._inspect_baseline()
	check(not ui.replaying and ui.events_list.get_meta("receipt") == ui.initial_run, "Switching comparisons cancels playback of the previous snapshot.")
	ui._populate_events(ui.latest_run)
	await capture("m1-cache-result")
	ui._toggle_replay()
	ui.editor.text = "broken draft"
	ui.editor.text_changed.emit()
	check(not ui.replaying and ui.editor.get_line_background_color(0) == Color.TRANSPARENT, "Editing pauses old playback and clears stale source focus.")
	ui.run_button.pressed.emit()
	check(signature == ui.latest_run["signature"] and ui.completed, "Invalid draft keeps previous immutable run and historical completion.")
	ui.undo()
	check(ui.editor.text == PerformanceTask.ROW_SOURCE, "Undo restores the program without injecting any reference.")
	ui._continue_task()
	check(ui.task_id == "d2_group", "Completed access order unlocks grouping.")
	ui.change_option("group", 1)
	ui.run_current()
	check(ui.completed and ui.latest_run["metrics"]["total_cycles"] == 138, "Grouping preserves both passes at 138 cycles.")
	ui._continue_task()
	ui.change_option("cache", 4)
	ui.run_current()
	check(ui.completed, "Capstone accepts more cache without a diagnosis gate.")
	ui.change_option("cache", 1)
	ui.change_option("group", 1)
	ui.run_current()
	check(ui.completed and ui.best_run["metrics"]["hardware_cost"] == 4, "Capstone accepts simultaneous edits and retains lower-cost best.")
	await capture("m3-final-result")
	check(progress.task_complete("d2_final"), "All eight mainline tasks complete in ordinary Game.")
	check(root.get_node("GlobalSave").game_player_content.completed_levels.is_empty(), "Mainline never fabricates workshop completions.")
	progress.storage_path = "res://.godot/redesign/full-route-%d.json" % Time.get_ticks_usec()
	progress.writes_enabled = true
	check(progress.save_game(), "Complete route is saved through the real atomic writer.")
	progress.game = progress._empty()
	check(progress.load_game(), "Complete route restores from its serialized file.")
	for id: String in progress.IDS:
		check(progress.task_complete(id), "Serialized accepted designs independently replay for " + id)
	ui.load_task("d2_final")
	check(ui.latest_run.is_empty() and ui.best_run["metrics"]["hardware_cost"] == 4, "Re-entry labels recomputed personal best separately from an unrun draft.")
	ui._open_handbook()
	ui.handbook._show_term(&"cpu_wait")
	check("158" in ui.handbook.detail_body_label.text and "134" in ui.handbook.detail_body_label.text, "Unified Handbook appends replayed mainline experience to the related term.")
	await capture("m4-handbook")
	ui.handbook.close_handbook()
	var legacy: Node = root.get_node("LocalityChapter")
	legacy.game_completed[&"nearby_storage"] = true
	ui._open_handbook()
	ui.handbook._show_term(&"cache")
	check(root.get_node("Localization").text(&"demo.legacy_experience") in ui.handbook.detail_body_label.text, "Existing Notebook experience remains visibly historical inside the unified Handbook.")
	legacy.game_completed.clear()
	ui.handbook.close_handbook()
	for dimensions: Vector2i in [Vector2i(1280, 720), Vector2i(1600, 900), Vector2i(1920, 1080)]:
		root.size = dimensions
		await process_frame
		await process_frame
		check(ui.get_global_rect().encloses(ui.run_button.get_global_rect()) and ui.get_global_rect().encloses(ui.continue_button.get_global_rect()), "Performance Run/Continue fit the viewport at %s." % dimensions)
		check(ui.editor.get_global_rect().end.x <= ui.memory_grid.get_global_rect().position.x, "Program and address table remain side by side at %s." % dimensions)
		check(ui.get_global_rect().encloses(ui.detail_scroll.get_global_rect()), "Expandable record controls remain inside the viewport at %s." % dimensions)
	progress.writes_enabled = false
	ui.load_task("dp_select")
	ui.circuit_board.graph.disconnection_request.emit(&"A", 0, &"MUX", 0)
	ui.run_current()
	check(not ui.latest_run["passed"] and progress.task_complete("d2_final"), "Revisiting and changing a foundation draft after performance tasks preserves accepted route history.")
	ui.free()
	if failures.is_empty():
		print("PASS: complete eight-task ordinary Game route, staged storage, immediate completion, draft isolation and multiple capstone solutions")
	quit(0 if failures.is_empty() else 1)

func wire(ui: Control, from: StringName, from_port: int, to: StringName, to_port: int) -> void:
	ui.circuit_board.graph.connection_request.emit(from, from_port, to, to_port)
