extends "res://tests/test_creation_workbench.gd"
## Known-answer rendered UI route; no human-understanding claim.
func run() -> void:
	root.get_node("TaskNavigation").pending = ""
	var packed: PackedScene = load("res://experiments/creation/workbench.tscn")
	var localization: Node = root.get_node("Localization")
	for locale: String in ["zh_CN","en"]:
		localization.set_locale(locale)
		var scene: Control = packed.instantiate(); root.add_child(scene); await settle()
		root.mode = Window.MODE_WINDOWED; root.size = Vector2i(1280,720); root.content_scale_size = Vector2i(1280,720)
		await settle()
		var locale_path: String = "user://creation-candidate/rendered-"+locale+".json"
		var opened: Dictionary = scene.session.open(locale_path)
		check(opened.get("writable",false),"Each locale uses its own writable QA session")
		scene.writable = bool(opened.get("writable",false))
		scene.session.data = preload("res://experiments/creation/session.gd").fresh()
		scene.change_task(2); await settle()
		await press(scene,"Train")
		var identity: String = Model.identity(scene.session.data.model)
		for condition: int in 2:
			await press(scene,"MachineCondition"+str(condition))
			await press(scene,"RunCostComparison")
			check(Model.identity(scene.session.data.model)==identity,"Machine intervention keeps learned rules")
			await capture("condition-%d-"%condition+locale)
		check(scene.transport_comparisons.size()==2,"Both immutable machine observations remain available")
		var ledger = preload("res://experiments/creation/cost_ledger.gd")
		var a: Dictionary = scene.transport_comparisons[0]
		var b: Dictionary = scene.transport_comparisons[1]
		check(ledger.total(a,"raw","total_cycles")<ledger.total(a,"predictive","total_cycles") and ledger.total(b,"raw","total_cycles")>ledger.total(b,"predictive","total_cycles"),"Actual UI conditions reverse the measured winner")
		await press(scene,"ReturnToSignal")
		await press(scene,"ToPredict")
		await press(scene,"Practice")
		await press(scene,"Commit")
		check(scene.session.prediction.rows.is_empty(),"First native-view guess leaves truth sealed")
		await capture("sealed-"+locale)
		await press(scene,"Reveal")
		bounds(scene,["ContinuePrediction","PredictionUntilMismatch","Status"])
		await press(scene,"PredictionUntilMismatch")
		check(not scene.session.prediction.rows[-1].correct,"Real mismatch stops for causal inspection")
		check(scene.focused_cell==scene.session.prediction.rows[-1].index,"Mismatch selection points to authoritative row")
		await capture("mismatch-"+locale)
		await press(scene,"ContinuePrediction")
		check(scene.session.prediction.finished,"Prediction completes without future shortcut")
		scene.change_task(7); await settle()
		await press(scene,"ToGenerate")
		scene.change_task(7); await settle()
		await press(scene,"Generate")
		await press(scene,"PinCreationAQuick")
		var pinned: Array = scene.pinned_creation.output.duplicate()
		var tabs: TabContainer = control(scene,"DraftTabs")
		tabs.current_tab = 0; await settle()
		await press(scene,"RemoveExample1")
		await press(scene,"Train")
		await press(scene,"Generate")
		check(scene.creation_report.get("controlled_effect",false) and scene.creation_report.first_difference>=0,"One example intervention produces controlled visible divergence")
		check(scene.pinned_creation.output==pinned,"A survives B learning and generation")
		tabs = control(scene,"DraftTabs"); tabs.current_tab = 2; await settle()
		await capture("controlled-pair-"+locale)
		await press(scene,"CreationFirstDifference")
		await capture("first-difference-"+locale)
		scene.name_input.text = "QA · retained A · "+locale
		await press(scene,"KeepCreationA")
		check(scene.session.data.works.size()==1 and scene.session.data.works[0].output==pinned,"Choosing A saves visible actual A")
		scene.name_input.text = "QA · chosen B · "+locale
		tabs = control(scene,"DraftTabs"); tabs.current_tab = 2; await settle()
		await press(scene,"KeepCreationB")
		check(scene.session.data.works.size()==2 and not scene.session.dirty,"Choosing B keeps both named works transactionally")
		var works: ItemList = control(scene,"Works"); works.select(1)
		await press(scene,"FocusWork")
		await capture("saved-work-"+locale)
		check(scene.work_focus.canvas.output==scene.session.data.works[1].output,"Full artwork equals confirmed snapshot")
		var close: Button = scene.work_focus.close_button
		close.pressed.emit(); await settle()
		await press(scene,"ReplayWork")
		check(scene.latest.get("matches",false),"Chosen B recipe reproduces exact saved output")
		var protected_work: Dictionary = scene.session.data.works[1].duplicate(true)
		await press(scene,"ForkWork")
		check(scene.session.data.works[1]==protected_work,"Fork leaves the complete chosen work immutable")
		await press(scene,"SaveDraft")
		scene.queue_free(); await settle()
		var resumed = packed.instantiate(); root.add_child(resumed); await settle()
		resumed.session.open(locale_path)
		check(resumed.session.data.works.size()==2 and resumed.session.data.works[1]==protected_work,"Host reopen preserves snapshot and full recipe")
		check(resumed.session.replay_work(1).get("matches",false),"Reopened recipe remains reproducible")
		var folder: String = "res://.godot/creation-captures"
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(folder))
		var artifact := FileAccess.open(folder.path_join("chosen-work-"+locale+".json"),FileAccess.WRITE)
		artifact.store_string(JSON.stringify(protected_work,"\t")); artifact.close()
		resumed.queue_free(); await settle()
	print("PASS: rendered creation playable loop checks=",checks) if failures==0 else print("FAIL: playable loop failures=",failures," / ",checks)
	quit(0 if failures==0 else 1)
