from pathlib import Path
import json,hashlib,plistlib,subprocess,uuid
root=Path.cwd();receipt=max((root/'.godot/package-qa').glob('*/result.json'),key=lambda p:p.stat().st_mtime);report=json.loads(receipt.read_text());assert report['source_commit']=='67334e386aa6700505984d1e5af2703397b8aace' and report['passed']
work=receipt.parent;app=Path(report['qa_app']);info=plistlib.loads((app/'Contents/Info.plist').read_bytes());binary=app/'Contents/MacOS'/info['CFBundleExecutable'];pack=app/'Contents/Resources'/(info['CFBundleExecutable']+'.pck');before={str(p.relative_to(app)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [binary,pack]}
probe=work/'creative-package-probe.gd';probe.write_bytes((root/'.godot/package-creative-probe.gd').read_bytes());scene=work/'creative-package-probe.tscn';scene.write_text('[gd_scene load_steps=2 format=3]\n[ext_resource type="Script" path='+json.dumps(str(probe))+' id="1"]\n[node name="CreativePackageProbe" type="Node"]\nscript = ExtResource("1")\n')
profile=report['user_suffix']+'-creative-'+uuid.uuid4().hex[:6]
override=binary.parent/'override.cfg';settings='[application]\nconfig/use_custom_user_dir=true\nconfig/custom_user_dir_name='+json.dumps(profile)+'\n';override.write_text(settings+'run/main_scene='+json.dumps(str(scene))+'\n')
r=subprocess.run(['/usr/bin/sandbox-exec','-f',str(work/'protect-player.sb'),str(binary),'--headless','--quit-after','600','--log-file',str(work/'creative-engine.log')],cwd=work,capture_output=True,text=True,timeout=60);log=r.stdout+r.stderr;(work/'creative-probe.log').write_text(log);override.write_text(settings)
line=next((x for x in log.splitlines() if x.startswith('CREATIVE_PACKAGE_CHECKS ')),None);checks=json.loads(line.removeprefix('CREATIVE_PACKAGE_CHECKS ')) if line else {};passed=r.returncode==0 and bool(checks) and all(checks.values()) and 'SCRIPT ERROR' not in log and 'ERROR:' not in log
assert {str(p.relative_to(app)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [binary,pack]}==before
(work/'creative-result.json').write_text(json.dumps({'source_commit':report['source_commit'],'checks':checks,'passed':passed,'exit':r.returncode,'binary_pack_sha256':before,'profile':profile,'evidence_kind':'actual exported binary controller fixture; no native OS input'},indent=2)+'\n');print('Creative actual package: '+str(passed)+' '+str(work));raise SystemExit(0 if passed else 1)
