extends SceneTree
## Documentation generated from the runtime catalog; never used to unlock tasks.
func _init() -> void: call_deferred("run")
func run() -> void:
	var navigation: Node=root.get_node("TaskNavigation")
	var localization: Node=root.get_node("Localization")
	localization.set_locale("en")
	var english: Dictionary={}
	for task: Dictionary in navigation.tasks(): english[task.key]=task.title
	localization.set_locale("zh_CN")
	var rows: Array[Dictionary]=navigation.tasks()
	var profiles: Dictionary={
		"hardware_foundations":["Free parts/wiring; truth-table or clocked cases", "named workbench", "prologue_simulation, hardware_foundations_ui, hardware_prologue_ui"],
		"chapter_1":["CPU/RAM/Bus choices, wiring and task-specific DSL", "separate draft/applied/parts/wiring + replayed observations", "system_lab_simulation, system_lab_ui, system_applications, chapter_workspaces"],
		"chapter_2":["Allowed cache/work-group choices, DSL, diagnosis and observed comparisons", "separate draft/applied/configuration + replayed observations", "locality_chapter_ui, simulation, chapter_workspaces"],
		"chapter_3":["Buffers/cache, request/state scheduling and DSL", "board + program drafts and source-validated solutions", "overlap_simulation, overlap_ui"],
		"chapter_4":["Field grouping/order, direct/full/batch copy and bounded scratch", "layout drafts, named layouts and recomputed solutions", "layout_simulation, layout_ui"]}
	var lines: Array[String]=["# Task maintenance matrix", "", "Generated by `scripts/export-task-matrix.gd` from TaskNavigation and the five catalogs.", "This is an inventory, not proof of a native playthrough or a second unlock authority.", "", "All tasks retain independent, voluntarily requested Hint tiers; local results never trust stored metrics.", "Per-task alternative and negative-solution evidence must be checked in the linked suites and dated verification records; absent evidence remains pending.", "", "| Task | Title | Prerequisites | Route | Decisions / verifier | Persistence | Metrics | Suites |", "|---|---|---|---|---|---|---|---|"]
	for task: Dictionary in rows:
		var profile: Array=profiles[task.domain]
		lines.append("| %s | %s | %s | %s | %s | %s | %s | %s |"%[task.key,(task.title+" / "+str(english[task.key])).replace("|","/"),", ".join(task.dependencies),"optional" if task.optional else "main",profile[0],profile[1],", ".join(task.record_metrics),profile[2]])
	lines.append("")
	lines.append("## Review one changed task")
	lines.append("Check its catalog definition/cases, progression evaluator, failed-case feedback, allowed tool set, save replay, three Hint reveal boundaries, and both localization catalogs. Run the listed suites plus content_registry/localization/task_tree. Use a non-reference solution and a wrong/over-budget example through the ordinary Game UI. Record actual outcomes; do not tick a row from this inventory alone.")
	var output: String="res://task-matrix.md"
	for argument: String in OS.get_cmdline_user_args():
		if argument.begins_with("--output="):output=argument.trim_prefix("--output=")
	var file:=FileAccess.open(output,FileAccess.WRITE)
	if file==null:push_error("Cannot write task matrix");quit(1);return
	file.store_string("\n".join(lines)+"\n");file.close()
	print("PASS: generated %d catalog tasks without changing progression"%rows.size());quit(0)
